INSERT INTO TRAINEE (traineeID, name) VALUES (1, 'Michael Massey')
INSERT INTO TRAINEE (traineeID, name) VALUES (2, 'Jarad Huggard')
INSERT INTO TRAINEE (traineeID, name) VALUES (3, 'Daryl Conway')
INSERT INTO SUBJECT (id, subjectName, subjectRating, traineeID) VALUES (1, 'Java', '3', 1)
INSERT INTO SUBJECT (id, subjectName, subjectRating, traineeID) VALUES (2, 'JavaScript', '3', 1)
INSERT INTO SUBJECT (id, subjectName, subjectRating, traineeID) VALUES (3, 'Databases', '4', 1)
INSERT INTO SUBJECT (id, subjectName, subjectRating, traineeID) VALUES (4, 'CI', '1', 1)
INSERT INTO SUBJECT (id, subjectName, subjectRating, traineeID) VALUES (5, 'Java', '4', 2)
INSERT INTO SUBJECT (id, subjectName, subjectRating, traineeID) VALUES (6, 'JavaScript', '3', 2)
INSERT INTO SUBJECT (id, subjectName, subjectRating, traineeID) VALUES (7, 'Databases', '5', 2)
INSERT INTO SUBJECT (id, subjectName, subjectRating, traineeID) VALUES (8, 'CI', '3', 2)
INSERT INTO SUBJECT (id, subjectName, subjectRating, traineeID) VALUES (9, 'Java', '4', 3)
INSERT INTO SUBJECT (id, subjectName, subjectRating, traineeID) VALUES (10, 'JavaScript', '4', 3)
INSERT INTO SUBJECT (id, subjectName, subjectRating, traineeID) VALUES (11, 'Databases', '5', 3)
INSERT INTO SUBJECT (id, subjectName, subjectRating, traineeID) VALUES (12, 'CI', '3', 3)